### ISSUE TITLE
Emoji Table page is broken

### ISSUE THREAD

**Issue by philippkuehn** [milesj/emojibase#133] opened 2021-10-11 19:13 UTC
I’m getting the following error at https://emojibase.dev/emojis/:

```
Uncaught (in promise) TypeError: (0 , i.t) is not a function
    at c5e36b27.1064ba1b.js:1
    at s (3749.e06c569f.js:2)
    at Generator._invoke (3749.e06c569f.js:2)
    at Generator.next (3749.e06c569f.js:2)
    at e (3749.e06c569f.js:2)
    at u (3749.e06c569f.js:2)
    at 3749.e06c569f.js:2
    at new Promise (<anonymous>)
    at 3749.e06c569f.js:2
    at c5e36b27.1064ba1b.js:1
```

**Comment by milesj** [comment] 2021-10-12 02:07
Ok so, this works locally, but I think the issue is that master (which auto-deploy docs) is about to release a new version, so it's kind of in a not finished state.

Resolving this will be tricky, so I'll just wait until the new version is released, which should be soon.

**Comment by milesj** [comment] 2021-10-15 23:56
This is working again.

**Closed by milesj** 2021-10-15 23:56 UTC
